### ISSUE TITLE
Off / RemoveListener does not remove Once events

### ISSUE THREAD

**Issue by m4ng0squ4sh** [chuckpreslar/emission#6]
Events attached with Once can't be removed with Off / RemoveListener.

Regards :)

**Comment by chuckpreslar** [comment]
good catch! can you throw some sample code at me with how you're using this just for some context? i may have to rethink the API that's exposed.

**Comment by chuckpreslar** [comment]
I've pushed a patch that should resolve this without creating any breaking changes. Can I get you to confirm this works for your scenario, @m4ng0squ4sh? If so, I'll leave it to you to close the issue! Thanks again, and sorry for the delay getting to this!

**Comment by m4ng0squ4sh** [comment]
Thank you for fixing it! Tried it and the bug is fixed :) Sorry for not providing some sample code. Was very busy...
